# src/configs/train/conf_0/data/default.yaml

modelClsName: base_model
modelClsArgs:
  local_patch_k: 3

  encoder_config:
    encoderClsName: base_encoder
    encoderClsArgs:
      in_channels: 3
      out_channels: 64

  decoder_config:
    decoderClsName: base_decoder
    decoderClsArgs:
      in_channels: ${eval:"64 * ${...local_patch_k} * ${...local_patch_k}"}
      out_channels: 3
