defaults:
  - _self_
  - data: default
  - model: default
  - train: default

common:
  normalize_config:
    normalize: true
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

  verbose: true
  experiment_name: exp_02

hydra:
  run:
    dir: logs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}