defaults:
  - _self_
  - data: default
  - model: default
  - train: default

common:
  normalize_config:
    normalize: true
    mean: [0.0, 0.0, 0.0]
    std: [1.0, 1.0, 1.0]

  verbose: true
  experiment_name: exp_xx

hydra:
  run:
    dir: logs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
