data:
  constructor: div2k_hr
  args:
    data_path: /dataroot/liujiang/data/datasets/DF2K
    train_ratio: 0.9
    seed: 42

phase: train

dataset:
  constructor: single_dataset
  args:
    lr_patch_size: 48
    scale: 2
    augment: true