# src/configs/train/conf_0/train/default.yaml

resume_config:
  resume: false
  resume_from_checkpointDir: null
  resume_from_checkpointEpoch: 0

common:
  optFuncArgsDic:
    adam:
      lr: 0.0001
      betas: [0.9, 0.999]
      weight_decay: 0

    sgd:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0

  scheFuncArgsDic:
    step_lr:
      step_size: 200
      gamma: 0.5

    exponential_lr:
      gamma: 0.95

  lossFuncArgsDic:
    l1_loss:
      reduction: mean

    mse_loss:
      reduction: mean

    cross_entropy:
      weight: null
      reduction: mean
      ignore_index: -100

trainerClsName: base_trainer
trainerClsArgs:
  component_config:
    optimizer_config:
      optimizerFuncName: adam
      optimizerFuncArgs: ${....common.optFuncArgsDic.${.optimizerFuncName}}

    scheduler_config:
      schedulerFuncName: step_lr
      schedulerFuncArgs: ${....common.scheFuncArgsDic.${.schedulerFuncName}}
    loss_config:
      lossFuncName: l1_loss
      lossFuncArgs: ${....common.lossFuncArgsDic.${.lossFuncName}}

  device: cuda
  max_epochs: 1000

  experiment_config:
    experiment_dir: ./experiments
    experiment_name: exp_01
    log_config:
      log_dir: logs
      log_step_interval: 200
      test_epoch_interval: 10
    test_config:
      test_metrics: [psnr, ssim]
    checkpoint_config:
      checkpoint_dir: checkpoints
      save_epoch_interval: 10
    hydra_config:
      origin_dir: ${hydra:run.dir}
